/**
 * Estimated cost calculation, **provider-aware**.
 *
 * The accounted tokens come from LangChain's `usage_metadata`, which
 * NORMALIZES the semantics across all providers:
 *
 *  1. `input_tokens` is ALWAYS the total of input tokens, INCLUSIVE of
 *     cache tokens (read and creation). The details are in
 *     `input_token_details.cache_read` / `cache_creation`.
 *     (E.g. @langchain/anthropic sums input + cache_creation + cache_read;
 *     OpenAI/Gemini already report the full prompt with cached ones included.)
 *     → for pricing, cache tokens must be subtracted from the full input and
 *       priced with their multiplier.
 *
 *  2. Cache price: if the model config has an explicit price
 *     ($ per 1M, from the provider's price list — e.g. DeepSeek "cache hit",
 *     Anthropic "cache writes 5m/1h") that one is used. Otherwise it
 *     falls back to default multipliers relative to the full input price:
 *     - Anthropic: read ×0.10, write (creation) ×1.25
 *     - OpenAI / compatible: cached input ×0.50 (no dedicated write cost)
 *     - DeepSeek: cache hit ×0.10
 *     - Gemini: cached ×0.25
 *     - Local providers (ollama/lmstudio): zero cost regardless
 */

export interface ModelPrice {
  /** $ per 1M input tokens. */
  inputPerM: number;
  /** $ per 1M output tokens. */
  outputPerM: number;
  /** $ per 1M tokens read from cache. If null/undefined → default multiplier. */
  cacheReadPerM?: number | null;
  /** $ per 1M cache write tokens. If null/undefined → default multiplier. */
  cacheWritePerM?: number | null;
}

export interface UsageTokens {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
}

/** Cache price multipliers (relative to the full input price), per provider. */
const CACHE_MULT: Record<string, { read: number; write: number }> = {
  anthropic:           { read: 0.10, write: 1.25 },
  openai:              { read: 0.50, write: 0 },
  'openai-compatible': { read: 0.50, write: 0 },
  deepseek:            { read: 0.10, write: 0 },
  gemini:              { read: 0.25, write: 0 },
};

/**
 * Estimated cost in $ of a group of tokens generated by a given provider.
 * The caller guarantees to have a valid price for the model.
 */
export function computeCost(provider: string, tokens: UsageTokens, price: ModelPrice): number {
  const mult = CACHE_MULT[provider] ?? { read: 1, write: 0 };

  // input_tokens (LangChain) already includes read+creation: subtracted so as not to count them twice.
  const fullInput = Math.max(0, tokens.inputTokens - tokens.cacheReadTokens - tokens.cacheWriteTokens);

  // Explicit cache price from the price list if configured, otherwise multiplier.
  const cacheReadPerM  = price.cacheReadPerM  ?? price.inputPerM * mult.read;
  const cacheWritePerM = price.cacheWritePerM ?? price.inputPerM * mult.write;

  const inCost     = (fullInput               / 1e6) * price.inputPerM;
  const cacheRCost = (tokens.cacheReadTokens   / 1e6) * cacheReadPerM;
  const cacheWCost = (tokens.cacheWriteTokens  / 1e6) * cacheWritePerM;
  const outCost    = (tokens.outputTokens      / 1e6) * price.outputPerM;

  return inCost + cacheRCost + cacheWCost + outCost;
}
