/**
 * @file egress-sync.service.ts
 *
 * Syncs the skill egress allowlist (C1) to the egress-proxy (Squid),
 * WITHOUT giving the skill any power to self-open domains.
 *
 * Flow:
 *   event that changes the allowlist (approve / enable / scope / remove / install ready)
 *     → SkillsService.getEgressAllowlist()  (union of the domains of enabled/approved skills)
 *     → EgressSyncService.sync(domains)
 *         → validates each domain (anti-injection of Squid directives)
 *         → renders an `acl allowed_domains dstdomain ...` file
 *         → ATOMICALLY writes the include file in EGRESS_DYNAMIC_DIR (shared volume)
 *     → the watcher inside the egress-proxy container detects the change → `squid -k reconfigure`
 *
 * The backend NEVER talks to the Docker socket or to Squid: it only writes a file.
 * If EGRESS_DYNAMIC_DIR is not configured (deploy without egress overlay) every
 * operation is a silent no-op.
 */
import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as fs from 'fs';
import * as path from 'path';

/** Name of the include file referenced by egress-proxy/squid.conf. */
const DYNAMIC_FILENAME = 'skill-domains.conf';

/**
 * Domain format accepted in `dstdomain`:
 *   - optional leading dot (Squid subdomain wildcard, e.g. `.example.com`)
 *   - DNS labels [a-z0-9-], non-empty, dot-separated
 *   - alphabetic TLD ≥ 2
 * Rejects spaces, slashes, `#`, `"` and any character that could inject
 * directives into the Squid config.
 */
const VALID_DOMAIN = /^\.?([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;

@Injectable()
export class EgressSyncService implements OnModuleInit {
  private readonly logger = new Logger(EgressSyncService.name);
  private readonly dynamicDir: string;

  constructor(private readonly config: ConfigService) {
    this.dynamicDir = (config.get<string>('EGRESS_DYNAMIC_DIR', '') || '').trim();
  }

  /** True if the egress overlay is active (include file dir configured). */
  private get enabled(): boolean {
    return this.dynamicDir.length > 0;
  }

  private get filePath(): string {
    return path.join(this.dynamicDir, DYNAMIC_FILENAME);
  }

  /**
   * At boot, if the egress overlay is active, ensures the file exists
   * (even empty) so that a possible first start of Squid does not fail.
   * The real content will be written by the first sync() of SkillsService.
   */
  async onModuleInit(): Promise<void> {
    if (!this.enabled) return;
    try {
      fs.mkdirSync(this.dynamicDir, { recursive: true });
      if (!fs.existsSync(this.filePath)) {
        this.writeAtomic(this.render([]));
        this.logger.log(`Dynamic egress file initialized: ${this.filePath}`);
      }
    } catch (err: any) {
      this.logger.warn(`Egress init failed (${this.filePath}): ${err.message}`);
    }
  }

  /**
   * Writes the allowlist to the include file. Idempotent: if the content does not change
   * it does NOT rewrite (avoids useless Squid reconfigures). No-op if the overlay is off.
   */
  async sync(domains: string[]): Promise<void> {
    if (!this.enabled) return;

    const valid: string[] = [];
    for (const raw of domains) {
      const d = (raw ?? '').trim().toLowerCase();
      if (!d) continue;
      if (VALID_DOMAIN.test(d)) {
        valid.push(d);
      } else {
        this.logger.warn(`Egress domain ignored (invalid format): "${raw}"`);
      }
    }
    valid.sort();

    const content = this.render(valid);
    try {
      const current = fs.existsSync(this.filePath)
        ? fs.readFileSync(this.filePath, 'utf8')
        : null;
      if (current === content) {
        this.logger.debug('Egress allowlist unchanged — no rewrite');
        return;
      }
      this.writeAtomic(content);
      this.logger.log(
        `Egress allowlist updated (${valid.length} domains) → ${this.filePath}`,
      );
    } catch (err: any) {
      this.logger.error(`Egress allowlist write failed: ${err.message}`);
    }
  }

  /** Renders the content of the Squid include file. */
  private render(domains: string[]): string {
    const header =
      '# === AUTOMATICALLY GENERATED by EgressSyncService (backend) ===\n' +
      '# Do not edit by hand: overwritten on every approve/enable/scope/remove.\n' +
      `# Domains: ${domains.length}\n`;
    if (domains.length === 0) {
      return header + '# (no domains declared by the enabled skills)\n';
    }
    // Same `allowed_domains` ACL as squid.conf: multiple lines add up.
    // One line per domain for readable diffs and clear logs.
    const lines = domains
      .map((d) => `acl allowed_domains dstdomain ${d}`)
      .join('\n');
    return header + lines + '\n';
  }

  /** Atomic write: temporary file in the same dir + rename. */
  private writeAtomic(content: string): void {
    fs.mkdirSync(this.dynamicDir, { recursive: true });
    const tmp = path.join(this.dynamicDir, `.${DYNAMIC_FILENAME}.tmp`);
    fs.writeFileSync(tmp, content, { encoding: 'utf8' });
    fs.renameSync(tmp, this.filePath);
  }
}
