import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn,
  UpdateDateColumn, ManyToOne, JoinColumn, Index,
} from 'typeorm';
import { User } from '../users/users.entity';

/** pending = proposed by extraction, awaiting user confirmation · confirmed = in active memory. */
export type UserMemoryStatus = 'pending' | 'confirmed';

/** Visibility of a note (F4): mirrors the platform's resource scoping. */
export type UserMemoryScope = 'personal' | 'team' | 'org';

/**
 * Persistent user memory: a durable fact about the user, valid across chats and sessions.
 *
 * Facts are proposed by automatic extraction (at a turn threshold) or on-demand,
 * stay `pending` until the user confirms them, and once `confirmed` they are
 * injected into the system prompt ("what I know about the user" block) — but only if the
 * user has enabled automatic memory (`User.autoMemoryEnabled`).
 */
@Entity('user_memory')
export class UserMemory {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: User;

  @Index('IDX_user_memory_user')
  @Column({ type: 'uuid' })
  userId: string;

  /** The stored fact (e.g. "Prefers concise answers in Italian"). */
  @Column({ type: 'text' })
  content: string;

  // ── A-MEM structured note (F1) ────────────────────────────────────────────
  // tags/keywords/context/category are generated by the summarizer at creation
  // (same call as the extraction; fire-and-forget for manual notes). Null/empty
  // when generation failed — the note is valid regardless.

  /** Classification labels (e.g. ["preferenze", "stack"]). */
  @Column({ type: 'jsonb', default: [] })
  tags: string[];

  /** Salient terms for full-text/hybrid retrieval (F2). */
  @Column({ type: 'jsonb', default: [] })
  keywords: string[];

  /** One-sentence relevance description ("when is this note useful"). */
  @Column({ type: 'text', nullable: true })
  context: string | null;

  /** Coarse bucket (e.g. 'preference' | 'profile' | 'constraint' | 'knowledge'). */
  @Column({ type: 'varchar', length: 64, nullable: true })
  category: string | null;

  /** Bidirectional links to related notes — filled by the evolution job (F3). */
  @Column({ type: 'jsonb', default: [] })
  linkedIds: string[];

  /** Always injected into the prompt, bypassing retrieval (F2). */
  @Column({ type: 'boolean', default: false })
  pinned: boolean;

  /**
   * Non-empty ⇒ this pending note is a MERGE PROPOSAL for those note ids:
   * on confirmation the originals are deleted and this one replaces them (F3).
   */
  @Column({ type: 'jsonb', default: [] })
  mergeOfIds: string[];

  /** Visibility (F4): personal | team (requires teamId) | org (admin-promoted). */
  @Column({ type: 'varchar', length: 20, default: 'personal' })
  scope: UserMemoryScope;

  @Column({ type: 'uuid', nullable: true })
  teamId: string | null;

  @Column({ type: 'varchar', length: 20, default: 'pending' })
  status: UserMemoryStatus;

  /** Chat the fact was extracted from (null if entered manually). */
  @Column({ type: 'uuid', nullable: true })
  sourceChatId: string | null;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
