import {
  Injectable, Logger, Inject, Optional,
  NotFoundException, ForbiddenException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { DynamicStructuredTool } from '@langchain/core/tools';
import { z } from 'zod';
import { UserMemory, UserMemoryScope } from './user-memory.entity';
import { Chat } from '../chats/chats.entity';
import { ChatsService } from '../chats/chats.service';
import { Message } from '../messages/messages.entity';
import { User } from '../users/users.entity';
import { AppConfigService } from '../app-config/app-config.service';
import { LlmProviderService } from '../app-config/llm-provider.service';
import { EmbeddingProviderService } from '../embed/embedding.provider.service';
import { VectorStoreProviderService } from '../vector-db/vector-store-provider.service';
import { runWithLlmCallContext } from '../usage/llm-call-context';
import { MemoryEvolutionService } from './memory-evolution.service';
import { TeamsService } from '../teams/teams.service';
import {
  SAVE_MEMORY_DESC, SEARCH_MEMORY_DESC, SEARCH_CONVERSATIONS_DESC,
  METADATA_SPEC, memoryExtractionPrompt,
} from '../prompts/prompts';

/** Maximum number of facts kept per user (the oldest confirmed ones are pruned). */
const MAX_FACTS_PER_USER = 50;
/** Maximum length of a single fact. */
const MAX_FACT_LEN = 300;

/** Fact proposed by extraction (already persisted as `pending`). */
export interface MemoryProposal {
  id:      string;
  content: string;
}

/** A-MEM note metadata, generated by the summarizer (F1). */
export interface NoteMetadata {
  tags: string[];
  keywords: string[];
  context: string | null;
  category: string | null;
}

/** Extraction output: fact + its metadata (single LLM call for the whole batch). */
export interface ExtractedNote extends NoteMetadata {
  content: string;
}

const EMPTY_METADATA: NoteMetadata = { tags: [], keywords: [], context: null, category: null };

// ── Hybrid retrieval (F2) ─────────────────────────────────────────────────────

/** Vector collection dedicated to the memory notes. */
const MEMORY_COLLECTION = 'user_memory';
/** Notes injected per message (upper bound; the cutoff can return fewer). */
const RETRIEVE_TOP_K = 8;
/** Candidates fetched from each leg before fusion. */
const CANDIDATE_LIMIT = 12;
/** Reciprocal-rank-fusion constant (standard 60). */
const RRF_K = 60;
/** A candidate found ONLY by the vector leg needs at least this similarity. */
const MIN_VECTOR_SCORE = 0.3;

/**
 * Reciprocal-rank fusion of the two retrieval legs. Pure function (unit-tested):
 * takes the ranked FTS ids and the vector hits (ranked, with similarity score),
 * drops vector-only candidates below MIN_VECTOR_SCORE, returns fused ids best-first.
 */
export function fuseHybrid(ftsIds: string[], vectorHits: Array<{ id: string; score: number }>): string[] {
  const fused = new Map<string, { score: number; inFts: boolean; vecScore: number }>();
  ftsIds.forEach((id, i) => {
    const e = fused.get(id) ?? { score: 0, inFts: false, vecScore: 0 };
    e.score += 1 / (RRF_K + i + 1);
    e.inFts = true;
    fused.set(id, e);
  });
  vectorHits.forEach((h, i) => {
    const e = fused.get(h.id) ?? { score: 0, inFts: false, vecScore: 0 };
    e.score += 1 / (RRF_K + i + 1);
    e.vecScore = Math.max(e.vecScore, h.score);
    fused.set(h.id, e);
  });
  return [...fused.entries()]
    .filter(([, e]) => e.inFts || e.vecScore >= MIN_VECTOR_SCORE)
    .sort((a, b) => b[1].score - a[1].score)
    .map(([id]) => id);
}


@Injectable()
export class UserMemoryService {
  private readonly logger = new Logger(UserMemoryService.name);

  constructor(
    @InjectRepository(UserMemory) private readonly repo: Repository<UserMemory>,
    @InjectRepository(Chat)       private readonly chatRepo: Repository<Chat>,
    @InjectRepository(Message)    private readonly messageRepo: Repository<Message>,
    @InjectRepository(User)       private readonly userRepo: Repository<User>,
    @Inject(AppConfigService)     private readonly appConfig: AppConfigService,
    @Inject(LlmProviderService)   private readonly llmProvider: LlmProviderService,
    @Inject(EmbeddingProviderService)  private readonly embedding: EmbeddingProviderService,
    @Inject(VectorStoreProviderService) private readonly vectorStore: VectorStoreProviderService,
    @Inject(TeamsService)         private readonly teams: TeamsService,
    @Inject(ChatsService)         private readonly chats: ChatsService,
    @Optional() private readonly evolution?: MemoryEvolutionService,
  ) {}

  /** TypeORM OR-conditions for the notes ACCESSIBLE to a user (F4). */
  private async accessibleWhere(userId: string, extra: Record<string, unknown> = {}): Promise<Record<string, unknown>[]> {
    const teamIds = await this.teams.teamIdsForUser(userId).catch(() => [] as string[]);
    return [
      { ...extra, scope: 'personal', userId },
      ...(teamIds.length ? [{ ...extra, scope: 'team', teamId: In(teamIds) }] : []),
      { ...extra, scope: 'org' },
    ];
  }

  // ── Retrieval for the system prompt ──────────────────────────────────────────

  /** Confirmed facts of the user, ready for injection into the prompt. */
  async getConfirmed(userId: string): Promise<string[]> {
    const rows = await this.repo.find({
      where: { userId, status: 'confirmed' },
      order: { createdAt: 'ASC' },
      select: { content: true },
    });
    return rows.map((r) => r.content);
  }

  /**
   * Pinned notes: always injected in the STABLE prompt prefix (they change
   * rarely, so they are cache-friendly — unlike the per-query retrieval).
   */
  async getPinnedContents(userId: string): Promise<string[]> {
    const rows = await this.repo.find({
      where: await this.accessibleWhere(userId, { status: 'confirmed', pinned: true }),
      order: { createdAt: 'ASC' },
      select: { content: true },
    });
    return rows.map((r) => r.content);
  }

  /**
   * Hybrid retrieval (F2): FTS + vector legs fused with RRF, relevance cutoff,
   * top-K cap. Resilient by construction: if the embedding service is down the
   * vector leg returns [] and retrieval degrades to FTS-only (and vice versa).
   * Pinned notes are excluded (already in the stable prefix).
   */
  async retrieve(userId: string, queryText: string): Promise<UserMemory[]> {
    const q = queryText?.trim();
    if (!q) return [];
    const t0 = Date.now();

    // OR-semantics FTS query: plainto_tsquery ANDs every word, which never
    // matches on a full user question. Tokenize (letters/digits only → safe
    // for to_tsquery), drop short words, cap the term count; ts_rank still
    // rewards notes matching MORE terms.
    const terms = [...new Set(
      q.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter((w) => w.length > 2),
    )].slice(0, 16);
    const orQuery = terms.join(' | ');

    const teamIds = (await this.teams.teamIdsForUser(userId).catch(() => [] as string[])).slice(0, 5);

    const [ftsIds, vectorHits] = await Promise.all([
      (orQuery
        ? this.repo.query(
            `SELECT "id" FROM "user_memory"
              WHERE "status" = 'confirmed' AND "pinned" = false
                AND (("scope" = 'personal' AND "userId" = $1)
                  OR ("scope" = 'team' AND "teamId" = ANY($3::uuid[]))
                  OR "scope" = 'org')
                AND "tsv" @@ to_tsquery('simple', $2)
              ORDER BY ts_rank("tsv", to_tsquery('simple', $2)) DESC
              LIMIT ${CANDIDATE_LIMIT}`,
            [userId, orQuery, teamIds],
          )
        : Promise.resolve([]))
        .then((rows: Array<{ id: string }>) => rows.map((r) => r.id))
        .catch((err: any) => { this.logger.warn(`Memory FTS failed: ${err?.message ?? err}`); return []; }),
      // Vector leg: adapter filters are AND-equality only → one search per
      // accessible scope, merged by best score (same trick as feedback-memory).
      this.embedding
        .embed(q)
        .then((vector) => Promise.all([
          this.vectorStore.search(MEMORY_COLLECTION, vector, CANDIDATE_LIMIT, { userId }),
          this.vectorStore.search(MEMORY_COLLECTION, vector, CANDIDATE_LIMIT, { scope: 'org' }),
          ...teamIds.map((t) => this.vectorStore.search(MEMORY_COLLECTION, vector, CANDIDATE_LIMIT, { scope: 'team', teamId: t })),
        ]))
        .then((all) => {
          const best = new Map<string, number>();
          for (const h of all.flat()) {
            const id = String(h.payload?.memoryId ?? h.id);
            best.set(id, Math.max(best.get(id) ?? 0, h.score));
          }
          return [...best.entries()].map(([id, score]) => ({ id, score })).sort((a, b) => b.score - a.score);
        })
        .catch((err: any) => { this.logger.debug(`Memory vector leg unavailable: ${err?.message ?? err}`); return []; }),
    ]);

    const orderedIds = fuseHybrid(ftsIds, vectorHits).slice(0, RETRIEVE_TOP_K);
    if (!orderedIds.length) return [];

    const notes = await this.repo.find({
      where: await this.accessibleWhere(userId, { id: In(orderedIds), status: 'confirmed', pinned: false }),
    });
    const byId = new Map(notes.map((n) => [n.id, n]));
    const result = orderedIds.map((id) => byId.get(id)).filter((n): n is UserMemory => !!n);
    this.logger.debug(
      `Memory retrieval: ${result.length} notes (fts=${ftsIds.length}, vec=${vectorHits.length}) in ${Date.now() - t0}ms`,
    );
    return result;
  }

  // ── Vector index maintenance (F2) ────────────────────────────────────────────

  /** Indexes a confirmed note in the vector collection. Best-effort. */
  private async indexNote(note: UserMemory): Promise<void> {
    if (note.status !== 'confirmed') return;
    try {
      const text = [note.content, note.context ?? '', (note.keywords ?? []).join(' ')].join('\n').trim();
      const vector = await this.embedding.embed(text);
      await this.vectorStore.ensureCollection(MEMORY_COLLECTION, this.embedding.vectorSize);
      await this.vectorStore.upsert(MEMORY_COLLECTION, [{
        id: note.id,
        vector,
        payload: {
          userId: note.userId, memoryId: note.id, tags: note.tags ?? [],
          category: note.category ?? null, scope: note.scope ?? 'personal', teamId: note.teamId ?? null,
        },
      }]);
    } catch (err: any) {
      this.logger.warn(`Memory indexing failed (${note.id}): ${err?.message ?? err}`);
    }
  }

  /** Removes a note from the vector collection. Best-effort. */
  private async deindexNote(id: string): Promise<void> {
    await this.vectorStore.deleteByFilter(MEMORY_COLLECTION, { memoryId: id }).catch(() => {});
  }

  /**
   * One-shot backfill (and embedding-provider change recovery): enriches the
   * user's confirmed notes still missing metadata and (re)indexes them all.
   */
  async reindexAll(userId: string): Promise<{ enriched: number; indexed: number }> {
    const notes = await this.repo.find({ where: { userId, status: 'confirmed' } });
    let enriched = 0;
    for (const note of notes) {
      if (!note.tags?.length && !note.context) {
        await this.enrichNote(note.id, note.content);  // sequential: gentle on the summarizer
        enriched++;
      }
    }
    const refreshed = await this.repo.find({ where: { userId, status: 'confirmed' } });
    for (const note of refreshed) await this.indexNote(note);
    this.logger.log(`Memory reindex (user ${userId}): ${enriched} enriched, ${refreshed.length} indexed`);
    return { enriched, indexed: refreshed.length };
  }

  /**
   * Changes a note's visibility (F4). Owner only; 'team' requires membership
   * of the target team; 'org' requires admin. The vector payload is refreshed.
   */
  async setScope(userId: string, id: string, scope: UserMemoryScope, teamId: string | null, isAdmin: boolean): Promise<UserMemory> {
    const fact = await this.repo.findOne({ where: { id } });
    if (!fact) throw new NotFoundException('userMemory.notFound');
    if (fact.userId !== userId && !isAdmin) throw new ForbiddenException();
    if (scope === 'org' && !isAdmin) throw new ForbiddenException('userMemory.orgRequiresAdmin');
    if (scope === 'team') {
      const teams = await this.teams.teamIdsForUser(userId);
      if (!teamId || !teams.includes(teamId)) throw new ForbiddenException('userMemory.notATeamMember');
    }
    fact.scope = scope;
    fact.teamId = scope === 'team' ? teamId : null;
    const saved = await this.repo.save(fact);
    await this.indexNote(saved);   // payload carries scope/teamId → refresh
    return saved;
  }

  /** Pins/unpins a note (pinned = always injected, bypasses retrieval). */
  async setPinned(userId: string, id: string, pinned: boolean): Promise<UserMemory> {
    const fact = await this.repo.findOne({ where: { id } });
    if (!fact) throw new NotFoundException('userMemory.notFound');
    if (fact.userId !== userId) throw new ForbiddenException();
    fact.pinned = pinned;
    return this.repo.save(fact);
  }

  // ── Management (Profile dashboard) ────────────────────────────────────────────

  /** All facts of the user (confirmed + pending), most recent first. */
  async listAll(userId: string): Promise<UserMemory[]> {
    const where = await this.accessibleWhere(userId);
    // Own pending proposals stay visible; shared notes appear once confirmed.
    return this.repo.find({
      where: [{ userId }, ...where.map((w) => ({ ...w, status: 'confirmed' as const }))],
      order: { createdAt: 'DESC' },
    });
  }

  /** Confirms one or more pending facts (transitions to `confirmed`). */
  async confirm(userId: string, ids: string[]): Promise<void> {
    if (!ids.length) return;
    await this.repo.update({ id: In(ids), userId }, { status: 'confirmed' });
    const confirmed = await this.repo.find({ where: { id: In(ids), userId } });
    // Confirmed MERGE proposals replace their originals (F3): delete + deindex them.
    for (const note of confirmed) {
      if (note.mergeOfIds?.length) {
        const originalIds = [...note.mergeOfIds];
        const originals = await this.repo.find({ where: { id: In(originalIds), userId } });
        if (originals.length) {
          // The merged note inherits the originals' links (minus themselves).
          const inherited: string[] = [...new Set<string>(originals.flatMap((o) => o.linkedIds ?? []))]
            .filter((id) => !originalIds.includes(id) && id !== note.id);
          note.linkedIds = [...new Set<string>([...(note.linkedIds ?? []), ...inherited])];
          await this.repo.remove(originals);
          for (const o of originalIds) void this.deindexNote(o);
          // Remap dangling references: notes linking an original now link the merged one.
          const referrers = await this.repo
            .query(`SELECT "id", "linkedIds" FROM "user_memory" WHERE "userId" = $1 AND "linkedIds" ?| $2`, [userId, originalIds])
            .catch(() => [] as Array<{ id: string; linkedIds: string[] }>);
          for (const r of referrers) {
            const remapped: string[] = [...new Set<string>((r.linkedIds ?? []).map((id: string) => (originalIds.includes(id) ? note.id : id)))]
              .filter((id) => id !== r.id);
            await this.repo.update(r.id, { linkedIds: remapped });
          }
          // Stale sibling proposals referencing the replaced notes are now moot.
          await this.repo
            .query(`DELETE FROM "user_memory" WHERE "userId" = $1 AND "status" = 'pending' AND "mergeOfIds" ?| $2`, [userId, originalIds])
            .catch(() => {});
          this.logger.log(`Merge confirmed (${note.id}): replaced ${originals.length} originals, remapped ${referrers.length} referrers`);
        }
        note.mergeOfIds = [];
        await this.repo.save(note);
      }
    }
    // Newly confirmed → enter the vector index + schedule the evolution round (F3).
    void Promise.all(confirmed.map((n) => this.indexNote(n))).catch(() => {});
    for (const n of confirmed) this.evolution?.enqueue(n.id);
    await this.pruneConfirmed(userId);
  }

  /** Keeps at most MAX_FACTS_PER_USER confirmed facts, discarding the oldest. */
  private async pruneConfirmed(userId: string): Promise<void> {
    const confirmed = await this.repo.find({
      where: { userId, status: 'confirmed', scope: 'personal' },
      order: { createdAt: 'DESC' },
      select: { id: true },
    });
    if (confirmed.length <= MAX_FACTS_PER_USER) return;
    const toDrop = confirmed.slice(MAX_FACTS_PER_USER).map((f) => f.id);
    await this.repo.delete({ id: In(toDrop) });
    void Promise.all(toDrop.map((id) => this.deindexNote(id)));
  }

  /** Inserts a manual fact already confirmed. Metadata generated asynchronously. */
  async addManual(userId: string, content: string): Promise<UserMemory> {
    const fact = this.repo.create({
      userId,
      content: content.trim().slice(0, MAX_FACT_LEN),
      status: 'confirmed',
      sourceChatId: null,
    });
    const saved = await this.repo.save(fact);
    await this.pruneConfirmed(userId);
    // Fire-and-forget: the note is valid even if enrichment fails (fields stay empty).
    void this.enrichNote(saved.id, saved.content);
    // Evolution round (F3): the job delay lets the enrichment land first.
    this.evolution?.enqueue(saved.id);
    return saved;
  }

  /**
   * Records a fact the agent was explicitly asked to remember ("ricordati che…").
   * Always created as `pending` (conservative-evolution decision: the user still
   * confirms it from the memory panel — the agent never writes active memory on
   * its own). Skips exact duplicates already in memory. Metadata is generated
   * fire-and-forget. Returns null when the content duplicates an existing note.
   */
  async proposeExplicit(userId: string, content: string, sourceChatId?: string | null): Promise<UserMemory | null> {
    const text = content.trim().slice(0, MAX_FACT_LEN);
    if (!text) return null;
    const existing = await this.repo.find({ where: { userId }, select: { content: true } });
    const norm = this.norm(text);
    if (existing.some((e) => this.norm(e.content) === norm)) return null;
    const fact = await this.repo.save(this.repo.create({
      userId, content: text, status: 'pending', sourceChatId: sourceChatId ?? null,
    }));
    void this.enrichNote(fact.id, fact.content);
    return fact;
  }

  // ── Episodic conversation search (F6) ─────────────────────────────────────────

  /**
   * Raw episodic recall (F6, Hermes-style): FTS over `messages.content`,
   * scoped to the chats the user can access (own chats + chats of accessible
   * projects). No LLM in the loop — complementary to the curated notes.
   * OR-tokenized like retrieve(): a full question must not AND every word.
   */
  async searchConversations(
    userId: string, queryText: string, limit = 6,
  ): Promise<Array<{ chatId: string; chatTitle: string; role: string; snippet: string; createdAt: Date }>> {
    const q = queryText?.trim();
    if (!q) return [];
    const terms = [...new Set(
      q.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter((w) => w.length > 2),
    )].slice(0, 16);
    const orQuery = terms.join(' | ');
    if (!orQuery) return [];
    const teamIds = (await this.teams.teamIdsForUser(userId).catch(() => [] as string[])).slice(0, 10);
    const cap = Math.min(Math.max(limit, 1), 10);
    try {
      const rows: Array<{ chatId: string; chatTitle: string | null; role: string; snippet: string; createdAt: Date }> =
        await this.messageRepo.query(
          `SELECT m."chatId", m."role", m."createdAt", c."title" AS "chatTitle",
                  ts_headline('simple', m."content", to_tsquery('simple', $2),
                    'MaxWords=28, MinWords=10, MaxFragments=1, StartSel=«, StopSel=»') AS "snippet"
             FROM "messages" m
             JOIN "chats" c ON c."id" = m."chatId"
            WHERE m."tsv" @@ to_tsquery('simple', $2)
              AND (c."userId" = $1
                OR c."projectId" IN (
                  SELECT p."id" FROM "projects" p
                   WHERE p."userId" = $1
                     OR p."id" IN (SELECT pt."projectId" FROM "project_teams" pt WHERE pt."teamId" = ANY($3::uuid[]))))
            ORDER BY ts_rank(m."tsv", to_tsquery('simple', $2)) DESC, m."createdAt" DESC
            LIMIT ${cap}`,
          [userId, orQuery, teamIds],
        );
      return rows.map((r) => ({
        chatId: r.chatId, chatTitle: r.chatTitle || 'Chat', role: r.role,
        snippet: (r.snippet || '').replace(/\s+/g, ' ').trim(), createdAt: r.createdAt,
      }));
    } catch (err: any) {
      this.logger.warn(`Episodic search failed: ${err?.message ?? err}`);
      return [];
    }
  }

  // ── Built-in tools for the agent (F5, class B) ────────────────────────────────

  /**
   * The two memory tools injected into the agent when the user has automatic
   * memory enabled (gated in agent.service, same as scheduling/sandbox).
   *   • save_memory  → proposes a durable fact as `pending` (NEVER auto-confirmed:
   *                    the user still approves it from the memory panel).
   *   • search_memory → hybrid retrieval BEYOND the top-K already injected, so the
   *                    agent can look up older/less-salient notes on demand.
   */
  buildMemoryTools(userId: string, chatId?: string): DynamicStructuredTool[] {
    const saveTool = new DynamicStructuredTool({
      name: 'save_memory',
      description: SAVE_MEMORY_DESC,
      schema: z.object({
        content: z.string().describe('The durable fact, a short self-contained sentence (e.g. "Prefers concise answers in Italian").'),
      }),
      func: async (args: any) => {
        const text = (args?.content ?? '').trim();
        if (!text) return 'Error: empty fact.';
        try {
          const note = await this.proposeExplicit(userId, text, chatId);
          if (!note) return 'That fact is already in memory — nothing to add.';
          return `Noted (awaiting your confirmation in the memory panel): "${note.content}".`;
        } catch (err: any) {
          return `Unable to save the memory: ${err?.message ?? err}`;
        }
      },
    });

    const searchTool = new DynamicStructuredTool({
      name: 'search_memory',
      description: SEARCH_MEMORY_DESC,
      schema: z.object({
        query: z.string().describe('What to look up (natural language, e.g. "database preferences").'),
      }),
      func: async (args: any) => {
        const query = (args?.query ?? '').trim();
        if (!query) return 'Error: empty query.';
        try {
          const notes = await this.retrieve(userId, query);
          if (!notes.length) return 'No relevant memory found.';
          return notes.map((n) => {
            const meta = [n.category, ...(n.tags ?? [])].filter(Boolean).join(', ');
            return `- ${n.content}${meta ? ` [${meta}]` : ''}`;
          }).join('\n');
        } catch (err: any) {
          return `Memory search failed: ${err?.message ?? err}`;
        }
      },
    });

    const searchConversationsTool = new DynamicStructuredTool({
      name: 'search_conversations',
      description: SEARCH_CONVERSATIONS_DESC,
      schema: z.object({
        query: z.string().describe('What was discussed (natural language or keywords, e.g. "backup schedule NAS").'),
      }),
      func: async (args: any) => {
        const query = (args?.query ?? '').trim();
        if (!query) return 'Error: empty query.';
        try {
          const hits = await this.searchConversations(userId, query);
          if (!hits.length) return 'No matching conversation found.';
          return hits.map((h) => {
            const date = h.createdAt instanceof Date ? h.createdAt.toISOString().slice(0, 10) : String(h.createdAt).slice(0, 10);
            return `- [${h.chatTitle} · ${date} · ${h.role}] ${h.snippet}`;
          }).join('\n');
        } catch (err: any) {
          return `Conversation search failed: ${err?.message ?? err}`;
        }
      },
    });

    return [saveTool, searchTool, searchConversationsTool];
  }

  /** Edits the text of a fact (owner). Metadata regenerated for the new content. */
  async update(userId: string, id: string, content: string): Promise<UserMemory> {
    const fact = await this.repo.findOne({ where: { id } });
    if (!fact) throw new NotFoundException('userMemory.notFound');
    if (fact.userId !== userId) throw new ForbiddenException();
    fact.content = content.trim().slice(0, MAX_FACT_LEN);
    const saved = await this.repo.save(fact);
    void this.enrichNote(saved.id, saved.content);
    return saved;
  }

  /** Deletes a fact (rejection of a pending one or deletion of a confirmed one). */
  async remove(userId: string, id: string): Promise<void> {
    const fact = await this.repo.findOne({ where: { id } });
    if (!fact) throw new NotFoundException('userMemory.notFound');
    if (fact.userId !== userId) throw new ForbiddenException();
    const removedId = fact.id;
    await this.repo.remove(fact);
    void this.deindexNote(removedId);
  }

  // ── Extraction ──────────────────────────────────────────────────────────────

  /** Effective threshold: per-user override > global default. */
  private async effectiveThreshold(user: Pick<User, 'memoryThreshold'>): Promise<number> {
    if (user.memoryThreshold != null) return user.memoryThreshold;
    const cfg = await this.appConfig.getToolLoadingConfig();
    return cfg.autoMemoryThreshold;
  }

  /**
   * True if since the last extraction (chat.memoryUpToMessageId) at least
   * `threshold` new messages have accumulated. Counts on the passed messages (history) to
   * avoid a query: includes both user and assistant turns.
   */
  async shouldExtract(
    user: Pick<User, 'memoryThreshold'>,
    chat: Pick<Chat, 'memoryUpToMessageId'>,
    history: Message[],
  ): Promise<boolean> {
    const threshold = await this.effectiveThreshold(user);
    if (threshold <= 0) return false;
    const newCount = this.freshMessages(chat.memoryUpToMessageId, history).length;
    return newCount >= threshold;
  }

  /** Messages not yet analyzed by extraction. */
  private freshMessages(upToId: string | null, history: Message[]): Message[] {
    if (!upToId) return history;
    const idx = history.findIndex((m) => m.id === upToId);
    return idx >= 0 ? history.slice(idx + 1) : history;
  }

  /**
   * Extracts new durable facts about the user from the "fresh" chat turns and
   * saves them as `pending` (awaiting confirmation). Updates `memoryUpToMessageId`.
   *
   * Best-effort and cross-provider: uses the summarizer model with a single
   * `invoke` on a text prompt. Errors → returns [] without propagating.
   *
   * @returns the saved proposals (pending), or [] if there is nothing new.
   */
  /**
   * Orchestration for the chat flow (end of turn): checks the user toggle and
   * the threshold, and if both are satisfied it extracts. Returns the proposals (or []).
   * Best-effort: intended to be called without blocking the response.
   */
  async maybeExtractOnTurn(userId: string, chat: Chat, history: Message[]): Promise<MemoryProposal[]> {
    const user = await this.userRepo.findOne({
      where: { id: userId },
      select: { id: true, autoMemoryEnabled: true, memoryThreshold: true },
    });
    if (!user?.autoMemoryEnabled) return [];
    if (!(await this.shouldExtract(user, chat, history))) return [];
    return this.extract(userId, chat.id, history);
  }

  /** On-demand variant: autonomously loads the chat history and extracts. */
  async extractForChat(userId: string, chatId: string): Promise<MemoryProposal[]> {
    // Authz: the caller must be able to access this chat. Without it, a user could
    // distill durable facts from another tenant's conversation by passing its chatId.
    // (The per-turn path maybeExtractOnTurn is already gated by the chat flow.)
    await this.chats.findOne(chatId, userId);
    const history = await this.messageRepo.find({
      where: { chatId },
      order: { createdAt: 'ASC' },
    });
    return this.extract(userId, chatId, history);
  }

  async extract(userId: string, chatId: string, history: Message[]): Promise<MemoryProposal[]> {
    try {
      const chat = await this.chatRepo.findOne({ where: { id: chatId } });
      if (!chat) return [];

      const fresh = this.freshMessages(chat.memoryUpToMessageId, history);
      if (!fresh.length) return [];

      const existing = await this.repo.find({
        where: { userId },
        select: { content: true },
      });
      const existingNorm = new Set(existing.map((e) => this.norm(e.content)));

      const notes = await this.extractNotes(fresh, existing.map((e) => e.content));

      // Filter out empty, too long, and duplicate ones (against existing memory and among themselves)
      const seen = new Set<string>(existingNorm);
      const fresh_notes: ExtractedNote[] = [];
      for (const raw of notes) {
        const f = (raw.content ?? '').trim().slice(0, MAX_FACT_LEN);
        if (!f) continue;
        const n = this.norm(f);
        if (seen.has(n)) continue;
        seen.add(n);
        fresh_notes.push({ ...raw, content: f });
      }

      // Always update the marker: even if there are no new facts, the turns
      // have been analyzed and must not be re-analyzed on the next trigger.
      chat.memoryUpToMessageId = fresh[fresh.length - 1].id;
      await this.chatRepo.save(chat);

      if (!fresh_notes.length) return [];

      const saved = await this.repo.save(
        fresh_notes.map((note) =>
          this.repo.create({ userId, ...note, status: 'pending', sourceChatId: chatId }),
        ),
      );

      this.logger.log(`User memory: ${saved.length} new facts proposed (user ${userId}, chat ${chatId})`);
      return saved.map((s) => ({ id: s.id, content: s.content }));
    } catch (err: any) {
      this.logger.warn(`Memory extraction failed (user ${userId}): ${err?.message ?? err}`);
      return [];
    }
  }

  /** Normalizes a fact for duplicate comparison (case/spaces/trailing punctuation). */
  private norm(s: string): string {
    return s.toLowerCase().replace(/\s+/g, ' ').replace(/[.!?;:,\s]+$/g, '').trim();
  }

  /**
   * Calls the summarizer model to extract durable facts about the user, each
   * with its A-MEM metadata (F1) — one LLM call for the whole batch.
   * Returns an array of notes (empty if there is nothing new).
   */
  private async extractNotes(turns: Message[], existing: string[]): Promise<ExtractedNote[]> {
    const model = await this.llmProvider.getSummarizerModel();

    const transcript = turns
      .map((m) => `${m.role === 'assistant' ? 'Assistant' : 'User'}: ${m.content}`)
      .join('\n');

    const prompt = memoryExtractionPrompt(transcript, existing);

    // Extraction is background work: it must never compete with interactive traffic.
    const res = await runWithLlmCallContext({ priority: 'background', origin: 'system' }, () => model.invoke(prompt));
    return this.parseNoteArray(this.contentToText(res.content));
  }

  /**
   * Generates the metadata for a single note (manual insert / content edit) and
   * updates the row. Fire-and-forget by contract: never throws, the note is
   * valid with empty metadata.
   */
  private async enrichNote(id: string, content: string): Promise<void> {
    try {
      const model = await this.llmProvider.getSummarizerModel();
      const prompt =
        'You annotate a long-term memory note about a user. ' +
        METADATA_SPEC + '\n\n' +
        `FACT: ${content}\n\n` +
        'Respond EXCLUSIVELY with one JSON object, without any additional text. Example: ' +
        '{"tags":["stack"],"keywords":["TypeScript","NestJS"],"context":"Useful when suggesting code.","category":"profile"}';
      const res = await runWithLlmCallContext({ priority: 'background', origin: 'system' }, () => model.invoke(prompt));
      const meta = this.sanitizeMetadata(this.parseJsonObject(this.contentToText(res.content)));
      await this.repo.update(id, meta);
      this.logger.debug(`Note ${id} enriched: [${meta.tags.join(', ')}] ${meta.category ?? ''}`);
      // Metadata changed → (re)index the confirmed note with the fresh text.
      const fresh = await this.repo.findOne({ where: { id } });
      if (fresh) await this.indexNote(fresh);
    } catch (err: any) {
      this.logger.warn(`Note enrichment failed (${id}): ${err?.message ?? err}`);
    }
  }

  /** Flattens an LLM response content (string or blocks) to plain text. */
  private contentToText(content: unknown): string {
    if (typeof content === 'string') return content;
    if (Array.isArray(content)) return content.map((b: any) => (b?.type === 'text' ? b.text : '')).join('');
    return '';
  }

  /** Bounds and normalizes LLM-generated metadata (never trust shapes blindly). */
  private sanitizeMetadata(raw: any): NoteMetadata {
    const strArr = (v: unknown, max: number, len: number): string[] =>
      Array.isArray(v)
        ? v.filter((x): x is string => typeof x === 'string' && !!x.trim())
            .map((x) => x.trim().slice(0, len)).slice(0, max)
        : [];
    return {
      tags:     strArr(raw?.tags, 3, 40).map((t) => t.toLowerCase()),
      keywords: strArr(raw?.keywords, 5, 60),
      context:  typeof raw?.context === 'string' && raw.context.trim() ? raw.context.trim().slice(0, 250) : null,
      category: typeof raw?.category === 'string' && raw.category.trim() ? raw.category.trim().toLowerCase().slice(0, 64) : null,
    };
  }

  /**
   * Robustly extracts a JSON array of notes from an LLM response. Tolerates
   * markdown fences, surrounding text, and the legacy string-array shape
   * (strings become notes with empty metadata).
   */
  private parseNoteArray(text: string): ExtractedNote[] {
    if (!text?.trim()) return [];
    const start = text.indexOf('[');
    const end = text.lastIndexOf(']');
    if (start < 0 || end <= start) return [];
    try {
      const parsed = JSON.parse(text.slice(start, end + 1));
      if (!Array.isArray(parsed)) return [];
      return parsed
        .map((x): ExtractedNote | null => {
          if (typeof x === 'string') return { content: x, ...EMPTY_METADATA };
          if (x && typeof x === 'object' && typeof x.content === 'string') {
            return { content: x.content, ...this.sanitizeMetadata(x) };
          }
          return null;
        })
        .filter((x): x is ExtractedNote => x !== null);
    } catch {
      return [];
    }
  }

  /** Robustly extracts the first JSON object from an LLM response. */
  private parseJsonObject(text: string): any {
    if (!text?.trim()) return null;
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start < 0 || end <= start) return null;
    try { return JSON.parse(text.slice(start, end + 1)); } catch { return null; }
  }
}
