import type { NetworkMode } from './runners/networks';

export interface InstallRequest {
  skill_id: string;
  python_deps: string[];   // e.g. ["pandas>=2.0", "numpy>=1.24"]
  js_deps: string[];       // e.g. ["lodash@4.17.21", "csv-parse@5.5.0"]
  nix_deps: string[];      // e.g. ["cowsay", "imagemagick", "ffmpeg"] — nixpkgs package names
}

export interface InstallResult {
  ok: boolean;
  log: string;
  duration_ms: number;
}

export interface ExecuteRequest {
  skill_id: string;
  filename: string;        // e.g. "scripts/analyze.py"
  language: 'python' | 'javascript' | 'node';
  input: Record<string, unknown>;
  timeout_ms?: number;     // default: MAX_TIMEOUT_MS env
  /**
   * Configuration variables resolved by the backend (system vars + user overrides).
   * Injected into the script as:
   *   Python / Node  → `_config` field in the stdin JSON (e.g. data["_config"]["OUTPUT_DIR"])
   *   JS (isolated)  → `config` global variable in the isolate (e.g. config.OUTPUT_DIR)
   */
  config?: Record<string, string>;
  /** Identity the skill runs as (C2) → USER_ID in the subprocess env. */
  user_id?: string;
  /** Run token signed by the backend → INTERNAL_TOKEN in the env (internal API auth). */
  run_token?: string;
  /**
   * Network tier of the job (D2, only via broker). See runners/networks.ts. The internal BE
   * network is the baseline; tiers add external reach on top:
   *   'internal'/undefined → BE only (no WAN).
   *   'internet' → also attach the egress network (sandboxnet + squid) → allowlisted domains
   *                via the proxy (set when the skill declared runtime.network).
   * ('open'/'none' are used by the sandbox, not by skill jobs.)
   */
  network?: NetworkMode;
  /**
   * Reserved Docker networks GRANTED to this skill by the admin (Phase 3): resolved
   * docker network names (LAN/VPN/subnets). The job is multi-homed onto them in addition
   * to the baseline. The broker re-validates each against BROKER_ALLOWED_NETWORKS.
   */
  grantedNetworks?: string[];
  /**
   * Files to stage in the per-job work dir (copy-in, C2 hard). Resolved and
   * AUTHORIZED by the backend (canAccess). The executor copies them into /work/inputs/ and
   * rewrites the `param` argument to the path in the container.
   */
  files?: { param: string; hostPath: string; name: string }[];
}

export interface ExecuteResult {
  stdout: string;
  stderr: string;
  exit_code: number;
  duration_ms: number;
  /** Top-level deliverables materialized in the per-user skills-output dir this run. */
  outputs?: string[];
}

// ─── Daemon types ─────────────────────────────────────────────────────────────

export interface DaemonStartRequest {
  skill_id:  string;
  daemon_id: string;       // UUID generated by the backend, used as the key in the daemon manager
  filename:  string;       // e.g. "scripts/daemon_emails.py"
  language:  'python' | 'node';
  config?:   Record<string, string>;
  user_id:   string;       // for notification routing in the backend
  push_url:  string;       // full URL: BACKEND_INTERNAL_URL/internal/daemons/events
  daemon_token?: string;   // signed daemon token → INTERNAL_TOKEN in the env
}

export interface DaemonStartResult {
  daemon_id:  string;
  pid:        number;
  started_at: string;      // ISO timestamp
}

export interface DaemonStopResult {
  daemon_id: string;
  stopped:   boolean;
}

export interface DaemonStatusEntry {
  daemon_id:  string;
  skill_id:   string;
  filename:   string;
  user_id:    string;
  pid:        number;
  running:    boolean;
  started_at: string;
}
