import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Multi-team projects.
 *
 * 1. `project_teams` — project↔team assignment with role (collaborator|viewer).
 *    A project can be shared with multiple teams (e.g. architects + sales).
 *
 * 2. Owner decoupling: `projects.userId` becomes nullable and the FK changes from
 *    ON DELETE CASCADE → ON DELETE SET NULL. This way, deleting the creator user
 *    does NOT destroy the project shared with the team (it stays orphaned, reassignable).
 *
 * The drop of the old FK is dynamic (looks up the constraint on userId) for robustness
 * against the name auto-generated by TypeORM.
 *
 * name = 'ProjectTeams1782500000041'
 */
export class ProjectTeams1782500000041 implements MigrationInterface {
  name = 'ProjectTeams1782500000041';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── 1. project_teams ──────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS project_teams (
        id          uuid NOT NULL DEFAULT uuid_generate_v4(),
        "projectId" uuid NOT NULL,
        "teamId"    uuid NOT NULL,
        role        varchar(20) NOT NULL DEFAULT 'collaborator',
        "addedAt"   TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT pk_project_teams PRIMARY KEY (id),
        CONSTRAINT uq_project_team UNIQUE ("projectId", "teamId"),
        CONSTRAINT fk_project_team_project FOREIGN KEY ("projectId")
          REFERENCES projects (id) ON DELETE CASCADE,
        CONSTRAINT fk_project_team_team FOREIGN KEY ("teamId")
          REFERENCES teams (id) ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_project_team_project ON project_teams ("projectId")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_project_team_team    ON project_teams ("teamId")`);

    // ── 2. Owner decoupling: userId nullable + FK ON DELETE SET NULL ───────
    // Dynamic drop of the existing FK on projects.userId (whatever its name is).
    await queryRunner.query(`
      DO $$
      DECLARE fk_name text;
      BEGIN
        SELECT con.conname INTO fk_name
        FROM pg_constraint con
        JOIN pg_attribute att
          ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
        WHERE con.conrelid = 'projects'::regclass
          AND con.contype = 'f'
          AND att.attname = 'userId';
        IF fk_name IS NOT NULL THEN
          EXECUTE format('ALTER TABLE projects DROP CONSTRAINT %I', fk_name);
        END IF;
      END $$;
    `);

    await queryRunner.query(`ALTER TABLE projects ALTER COLUMN "userId" DROP NOT NULL`);

    await queryRunner.query(`
      ALTER TABLE projects
        ADD CONSTRAINT fk_projects_owner FOREIGN KEY ("userId")
        REFERENCES users (id) ON DELETE SET NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Restore the CASCADE FK and NOT NULL (best-effort: orphaned projects
    // would need to be reassigned before NOT NULL can be put back).
    await queryRunner.query(`ALTER TABLE projects DROP CONSTRAINT IF EXISTS fk_projects_owner`);
    await queryRunner.query(`
      ALTER TABLE projects
        ADD CONSTRAINT "FK_361a53ae58ef7034adc3c06f09f" FOREIGN KEY ("userId")
        REFERENCES users (id) ON DELETE CASCADE
    `);
    await queryRunner.query(`DROP TABLE IF EXISTS project_teams`);
  }
}
