import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Adds the `schemaManifest` (jsonb) column to data_sources: the enriched
 * schema (tables/columns/comments/relations/deny) generated by introspection + AI
 * and editable by the user. Nullable: existing data sources remain without a manifest
 * until one is generated.
 *
 * name = 'DataSourceSchemaManifest1783800000055'
 */
export class DataSourceSchemaManifest1783800000055 implements MigrationInterface {
  name = 'DataSourceSchemaManifest1783800000055';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE data_sources ADD COLUMN IF NOT EXISTS "schemaManifest" jsonb`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE data_sources DROP COLUMN IF EXISTS "schemaManifest"`);
  }
}
