import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * A-MEM F1 (AMEM_DESIGN.md): user_memory evolves from flat fact to STRUCTURED
 * NOTE — tags/keywords/context/category generated by the summarizer at
 * creation, linkedIds filled by the evolution job (F3), pinned always injected
 * regardless of retrieval (F2). Existing rows keep null/empty values until the
 * one-shot backfill after F1+F2.
 *
 * name = 'UserMemoryNotes1785200000069'
 */
export class UserMemoryNotes1785200000069 implements MigrationInterface {
  name = 'UserMemoryNotes1785200000069';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "user_memory" ADD COLUMN IF NOT EXISTS "tags"      jsonb NOT NULL DEFAULT '[]'`);
    await queryRunner.query(`ALTER TABLE "user_memory" ADD COLUMN IF NOT EXISTS "keywords"  jsonb NOT NULL DEFAULT '[]'`);
    await queryRunner.query(`ALTER TABLE "user_memory" ADD COLUMN IF NOT EXISTS "context"   text`);
    await queryRunner.query(`ALTER TABLE "user_memory" ADD COLUMN IF NOT EXISTS "category"  varchar(64)`);
    await queryRunner.query(`ALTER TABLE "user_memory" ADD COLUMN IF NOT EXISTS "linkedIds" jsonb NOT NULL DEFAULT '[]'`);
    await queryRunner.query(`ALTER TABLE "user_memory" ADD COLUMN IF NOT EXISTS "pinned"    boolean NOT NULL DEFAULT false`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const col of ['tags', 'keywords', 'context', 'category', 'linkedIds', 'pinned']) {
      await queryRunner.query(`ALTER TABLE "user_memory" DROP COLUMN IF EXISTS "${col}"`);
    }
  }
}
