/**
 * @file internal-daemons.controller.ts
 *
 * Internal endpoint to receive events from daemon processes.
 *
 * Called exclusively by the skill executor (via PUSH_URL injected as an env var).
 * Protected by InternalTokenGuard — not reachable from browsers/users.
 *
 * Flow for each event:
 *   1. Update lastEventAt in the DB (daemon record)
 *   2. Special daemon_exit handling: update DB state
 *   3. Persist the notification in the DB (Notification entity) → get the DB id
 *   4. Emit via Socket.IO to the user (with the notification's DB id)
 *
 * Event format (Body JSON):
 * {
 *   skill_id:   string,
 *   user_id:    string,
 *   daemon_id:  string,
 *   event_type: string,   // e.g. 'new_emails', 'daemon_exit', 'error', ...
 *   payload:    object    // depends on the event_type
 * }
 */
import {
  Controller, Post, Body, Req, UseGuards, ForbiddenException,
  HttpCode, HttpStatus, Logger,
} from '@nestjs/common';
import { IsString, IsObject, IsOptional, IsUUID } from 'class-validator';

import { InternalTokenGuard }    from '../common/guards/internal-token.guard';
import { NotificationsGateway }   from '../notifications/notifications.gateway';
import { NotificationsService }   from '../notifications/notifications.service';
import { DaemonsService }         from './daemons.service';

class DaemonEventDto {
  @IsUUID()
  skill_id: string;

  @IsString()
  user_id: string;

  @IsString()
  daemon_id: string;

  @IsString()
  event_type: string;

  @IsOptional()
  @IsObject()
  payload?: Record<string, unknown>;
}

@UseGuards(InternalTokenGuard)
@Controller('internal/daemons')
export class InternalDaemonsController {
  private readonly logger = new Logger(InternalDaemonsController.name);

  constructor(
    private readonly daemonsSvc:     DaemonsService,
    private readonly notifications:  NotificationsGateway,
    private readonly notifSvc:       NotificationsService,
  ) {}

  /**
   * POST /internal/daemons/events
   *
   * Entry point for all events generated by daemon processes.
   * The daemon process calls this endpoint via PUSH_URL with the event_type
   * and the event-specific payload.
   */
  @Post('events')
  @HttpCode(HttpStatus.OK)
  async receiveEvent(
    @Body() dto: DaemonEventDto,
    @Req() req: { internalAuth?: { sub?: string; did?: string } },
  ): Promise<{ ok: boolean }> {
    // Authoritative identity from the signed DAEMON token (sub=owner, did=daemonId),
    // NOT from the body: a daemon must not update another daemon's state, spoof
    // notifications to another user, or DoS another tenant's daemon by passing
    // arbitrary user_id/daemon_id. Fail-closed if the token is not daemon-scoped.
    const userId   = req.internalAuth?.sub;
    const daemonId = req.internalAuth?.did;
    if (!userId || !daemonId) {
      throw new ForbiddenException('Daemon event requires a daemon-scoped token.');
    }
    if (dto.daemon_id !== daemonId || dto.user_id !== userId) {
      this.logger.warn(
        `[internal] daemon event body/token mismatch (token daemon=${daemonId.slice(0, 8)} ` +
        `user=${userId}; body daemon=${dto.daemon_id?.slice(0, 8)} user=${dto.user_id}) — using token`,
      );
    }

    this.logger.debug(
      `[internal] Evento daemon: daemon=${daemonId.slice(0, 8)} ` +
      `skill=${dto.skill_id.slice(0, 8)} user=${userId} type=${dto.event_type}`,
    );

    // 1. Update lastEventAt in the DB
    try {
      await this.daemonsSvc.recordEvent(daemonId);
    } catch { /* non-critical */ }

    // 2. Special handling for daemon_exit: update DB state
    if (dto.event_type === 'daemon_exit') {
      try {
        await this.daemonsSvc.handleDaemonExit(
          daemonId,
          (dto.payload?.exit_code as number | null) ?? null,
        );
      } catch { /* non-critical */ }
    }

    // 3. Persist the notification in the DB
    const timestamp = new Date().toISOString();
    let notifId: string | null = null;
    try {
      const saved = await this.notifSvc.create({
        userId,
        source:    'skill_daemon',
        sourceId:  daemonId,
        eventType: dto.event_type,
        payload:   {
          ...(dto.payload ?? {}),
          _skill_id: dto.skill_id,
        },
      });
      notifId = saved.id;
    } catch (err) {
      this.logger.error('[internal] Error saving notification', err);
      // Continue: the Socket.IO emit happens anyway
    }

    // 4. Notify the user via Socket.IO (includes the DB id for frontend consistency)
    this.notifications.emitToUser(userId, 'skill_event', {
      id:         notifId,           // may be null if the save failed
      daemon_id:  daemonId,
      skill_id:   dto.skill_id,
      event_type: dto.event_type,
      payload:    dto.payload ?? {},
      timestamp,
    });

    return { ok: true };
  }
}
