import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  Get,
  Inject,
  NotFoundException,
  Param,
  Patch,
  Post,
  Query,
  Req,
  Res,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import {FileInterceptor} from '@nestjs/platform-express';
import {ApiBearerAuth, ApiBody, ApiConsumes, ApiOperation, ApiQuery, ApiTags} from '@nestjs/swagger';
import {diskStorage} from 'multer';
import {basename, extname, resolve, join, sep} from 'path';
import {existsSync, realpathSync, statSync} from 'fs';
import {lookup as mimeLookup} from 'mime-types';
import {JwtService} from '@nestjs/jwt';
import {v4 as uuidv4} from 'uuid';
import type {Request, Response} from 'express';
import {JwtAuthGuard} from '../common/guards/jwt-auth.guard';
import {FileStreamAccessGuard} from './raw-file-access.guard';
import {CurrentUser} from '../common/decorators/current-user.decorator';
import {FilesService} from './files.service';
import {DataSourcesService} from '../datasources/datasources.service';

// No MIME restriction on the backend side: any file can be uploaded.
// The discrimination on what to do with the file (embed RAG / inline text / attachment)
// happens on the frontend side based on the type. Types not supported by extractText
// return an empty string without error.

/** UPLOAD_DIR / SKILLS_OUTPUT_DIR resolved to absolute at runtime (Docker + local dev). */
function uploadDirAbs(): string  { return resolve(process.env.UPLOAD_DIR ?? './uploads'); }
function skillsOutAbs(): string  { return resolve(process.env.SKILLS_OUTPUT_DIR ?? './uploads/skills-output'); }

/**
 * Max upload size in bytes from MAX_UPLOAD_MB (default 50 MB). Read from
 * process.env at decorator-evaluation time: in Docker the var is real process
 * env (env_file), so this is safe; changing it requires a backend restart.
 * The nginx proxy in the frontend container enforces the same env var
 * (client_max_body_size) — the request must pass both.
 */
function maxUploadBytes(): number {
  const mb = Number(process.env.MAX_UPLOAD_MB);
  return (Number.isFinite(mb) && mb > 0 ? mb : 50) * 1024 * 1024;
}

// NB: the guard is applied PER METHOD (not at the controller level) because
// GET /api/files/stream uses FileStreamAccessGuard (JWT bearer OR signed ?token=),
// while the other endpoints require the standard JWT bearer.
@ApiTags('files')
@ApiBearerAuth()
@Controller('api/files')
export class FilesController {
  constructor(
    @Inject(FilesService) private readonly service: FilesService,
    @Inject(JwtService) private readonly jwt: JwtService,
    @Inject(DataSourcesService) private readonly datasources: DataSourcesService,
  ) {}

  @Get()
  @UseGuards(JwtAuthGuard)
  findAll(
    @CurrentUser() user: any,
    @Query('projectId') projectId?: string,
    @Query('chatId') chatId?: string,
  ) {
    if (chatId) return this.service.findByChatId(chatId, user.id);
    if (projectId) return this.service.findByProject(projectId, user.id);
    return this.service.findByUser(user.id);
  }

  @Get('search')
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Access-scoped search on files (C2)' })
  @ApiQuery({ name: 'q', required: false })
  search(
    @CurrentUser() user: any,
    @Query('q') q?: string,
    @Query('limit') limit?: string,
  ) {
    return this.service.searchReadable(user.id, q ?? '', limit ? Number(limit) : 50);
  }

  @Post('upload')
  @UseGuards(JwtAuthGuard)
  @ApiConsumes('multipart/form-data')
  @ApiBody({ schema: { type: 'object', properties: { file: { type: 'string', format: 'binary' }, projectId: { type: 'string' } } } })
  @UseInterceptors(
    FileInterceptor('file', {
      storage: diskStorage({
        destination: './uploads',
        filename: (_req, file, cb) => cb(null, `${uuidv4()}${extname(file.originalname)}`),
      }),
      limits: { fileSize: maxUploadBytes() },
    }),
  )
  async upload(
    @UploadedFile() file: Express.Multer.File,
    @CurrentUser() user: any,
    @Query('projectId') projectId?: string,
    @Query('scope') scope?: 'personal' | 'team' | 'org',
    @Query('teamId') teamId?: string,
  ) {
    if (!file) throw new BadRequestException('files.uploadMissing');
    return this.service.saveFile(user.id, projectId || null, file, {
      scope: scope ?? 'personal',
      teamId: teamId || null,
    });
  }

  @Get(':id/download')
  @UseGuards(JwtAuthGuard)
  async download(@Param('id') id: string, @CurrentUser() user: any, @Res() res: Response) {
    const file = await this.service.findOneReadable(id, user.id);
    res.download(file.storagePath, file.originalName);
  }

  /**
   * Generic download of any file generated by the system (skill, tool, etc.).
   *
   * Accepts ONLY a path relative to the allowed directories:
   *   ?rel=skills-output/pdfs/report.pdf
   *
   * Security:
   *   - No absolute path: no arbitrary path from the client.
   *   - The rel is resolved against each allowed root; accepted only if,
   *     AFTER resolving symlinks (realpathSync), the real file stays CONTAINED
   *     within the real root → blocks "../" and symlinks pointing outside.
   *   - JWT required.
   *
   * For inline VIEWING/streaming (even of huge files on network shares) use
   * GET /api/files/stream instead.
   */
  @Get('raw')
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Generic download of a file generated by skill/tool' })
  @ApiQuery({ name: 'rel', description: 'Path relative to UPLOAD_DIR / SKILLS_OUTPUT_DIR', required: true })
  async serveRaw(
    @Query('rel') relPath: string | undefined,
    @CurrentUser() user: any,
    @Res() res: Response,
  ) {
    const real = this.resolveAllowedReal(relPath, user.id);
    // Access-aware: if it is a tracked File, verify canAccess (throw if denied).
    // Skill outputs live in the caller's OWN per-user subdir (resolveAllowedReal
    // confines to it), so an untracked hit here is by construction the caller's own.
    await this.service.assertReadableByAbsPath(real, user.id);
    return res.download(real);
  }

  /**
   * Issues a short-lived signed token, BOUND to the (`source`,`path`) pair,
   * that lets the browser access GET /api/files/stream DIRECTLY (e.g.
   * `<video src>` or a new tab) without an Authorization header → enables native
   * progressive streaming (Range requests).
   *
   * Requires a JWT bearer and verifies access to the file BEFORE issuing the token
   * (statFileShare applies the scope check and fails if the file is not reachable).
   */
  @Get('stream-token')
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Signed token for native streaming of a file from a source' })
  @ApiQuery({ name: 'source', description: "Source id ('local' or file-share DataSource id)", required: true })
  @ApiQuery({ name: 'path', description: 'File path relative to the source base', required: true })
  async streamToken(
    @Query('source') source: string | undefined,
    @Query('path') filePath: string | undefined,
    @CurrentUser() user: any,
  ) {
    if (!source || !filePath) {
      throw new BadRequestException('files.streamParamsRequired');
    }
    // Pre-validation of access + existence (scope check included): throws if denied.
    await this.datasources.statFileShare(source, user.id, filePath);
    // Short token but enough to watch/scrub a media (re-sent on every
    // Range request). Bound to sub + source + path: valid only for this file.
    const expiresIn = '2h';
    const token = this.jwt.sign(
      { sub: user.id, scope: 'file-stream', source, path: filePath },
      { expiresIn },
    );
    return { token, expiresIn };
  }

  /**
   * Inline STREAMING/viewing of a file from a source (local or network SMB/SFTP/
   * WebDAV), with HTTP `Range` support → progressive playback and seek in the browser
   * WITHOUT downloading/buffering the whole file (works even with videos of tens
   * of GB). Materializes nothing: reads in chunks directly from the source.
   *
   * Auth: Bearer JWT (axios) OR signed `?token=` (direct browser navigation).
   */
  @Get('stream')
  @UseGuards(FileStreamAccessGuard)
  @ApiOperation({ summary: 'Inline streaming/viewing of a file from a source (with Range)' })
  @ApiQuery({ name: 'source', description: "Source id ('local' or file-share DataSource id)", required: true })
  @ApiQuery({ name: 'path', description: 'File path relative to the source base', required: true })
  @ApiQuery({ name: 'dl', description: '1/true → forces the download (Content-Disposition: attachment) instead of inline viewing', required: false })
  @ApiQuery({ name: 'token', description: 'Signed token (alternative to the Bearer JWT) for direct browser navigation', required: false })
  async streamFile(
    @Query('source') source: string | undefined,
    @Query('path') filePath: string | undefined,
    @Query('dl') dl: string | undefined,
    @CurrentUser() user: any,
    @Req() req: Request,
    @Res() res: Response,
  ) {
    if (!source || !filePath) {
      throw new BadRequestException('files.streamParamsRequired');
    }

    const total = await this.datasources.statFileShare(source, user.id, filePath);
    const name  = basename(filePath.replace(/\/+$/, '')) || 'file';
    const type  = mimeLookup(name) || 'application/octet-stream';
    const disp  = dl === '1' || dl === 'true' ? 'attachment' : 'inline';

    res.setHeader('Content-Type', type);
    res.setHeader(
      'Content-Disposition',
      `${disp}; filename="${name.replace(/"/g, '')}"; filename*=UTF-8''${encodeURIComponent(name)}`,
    );
    res.setHeader('Accept-Ranges', 'bytes');
    res.setHeader('Cache-Control', 'private, max-age=0, must-revalidate');

    // ── Range parsing (endpoints inclusive; also handles the "bytes=-N" suffix) ──
    let start = 0;
    let end = total > 0 ? total - 1 : 0;
    let partial = false;
    const m = total > 0 && req.headers.range ? /^bytes=(\d*)-(\d*)$/.exec(req.headers.range) : null;
    if (m && !(m[1] === '' && m[2] === '')) {
      if (m[1] === '') {
        // Suffix: last N bytes
        const n = parseInt(m[2], 10);
        start = Math.max(0, total - n);
        end = total - 1;
      } else {
        start = parseInt(m[1], 10);
        end = m[2] === '' ? total - 1 : Math.min(parseInt(m[2], 10), total - 1);
      }
      partial = true;
      if (total > 0 && (start > end || start >= total)) {
        res.status(416).setHeader('Content-Range', `bytes */${total}`);
        res.end();
        return;
      }
    }

    const stream = await this.datasources.openFileShareStream(
      source, user.id, filePath, partial ? { start, end } : undefined,
    );
    // If the client aborts (seek/closes the tab) we close the stream → releases the
    // connection to the share.
    req.on('close', () => stream.destroy());
    stream.on('error', (err) => {
      this.serveStreamError(res, err);
    });

    if (partial) {
      res.status(206);
      res.setHeader('Content-Range', `bytes ${start}-${end}/${total}`);
      res.setHeader('Content-Length', String(end - start + 1));
    } else {
      res.setHeader('Content-Length', String(total));
    }
    stream.pipe(res);
  }

  private serveStreamError(res: Response, err: unknown): void {
    if (!res.headersSent) {
      res.status(500).end();
    } else {
      res.destroy(err instanceof Error ? err : undefined);
    }
  }

  /**
   * Resolves a `rel` (relative to UPLOAD_DIR / SKILLS_OUTPUT_DIR) into the real
   * absolute path, applying the same security guards:
   *   - no absolute paths / null byte;
   *   - after realpathSync, the real file must stay contained within the real root
   *     (blocks "../" and symlinks pointing outside).
   * @throws BadRequest if `rel` is missing/invalid; NotFound if not resolvable.
   */
  private resolveAllowedReal(relPath: string | undefined, userId: string): string {
    if (!relPath) {
      throw new BadRequestException('files.relRequired');
    }
    if (relPath.startsWith('/') || relPath.includes('\0')) {
      throw new BadRequestException('files.relInvalid');
    }
    const skillsRoot = skillsOutAbs();
    const userSkills = join(skillsRoot, userId || '_shared');
    // Skills compute their download_url relative to the PARENT of
    // SKILLS_OUTPUT_DIR (job layout convention → "skills-output/<path>"), while
    // the per-tenant confinement resolves rel against the caller's own subdir:
    // accept the prefixed form by stripping it for the skills root only. The
    // confinement is unchanged — the stripped rel still resolves (and is
    // containment-checked) inside the caller's own subdir.
    const relForSkills = relPath.replace(/^skills-output\//, '');
    // (root, rel, extra-guard). Skill outputs: only the caller's OWN per-user
    // subdir. Uploads: the flat UPLOAD_DIR, but NEVER reaching into the shared
    // skills-output tree (guards the per-user confinement when SKILLS_OUTPUT_DIR
    // is nested under UPLOAD_DIR — otherwise a ?rel=skills-output/<otherUser>/x
    // would bypass it).
    const roots: Array<[string, string, (real: string) => boolean]> = [
      [userSkills, relForSkills, () => true],
      [uploadDirAbs(), relPath, (real) => real !== skillsRoot && !real.startsWith(skillsRoot + sep)],
    ];
    for (const [dir, rel, ok] of roots) {
      let realDir: string;
      try { realDir = realpathSync(dir); } catch { continue; } // nonexistent root → skip
      const candidate = resolve(join(realDir, rel));
      let real: string;
      try {
        // Must exist AND be a regular file: a directory (e.g. rel='.') is not downloadable.
        if (!existsSync(candidate) || !statSync(candidate).isFile()) continue;
        real = realpathSync(candidate);
      } catch { continue; }
      if ((real === realDir || real.startsWith(realDir + sep)) && ok(real)) {
        return real;
      }
    }
    throw new NotFoundException('files.notFoundOrForbidden');
  }

  @Patch(':id/scope')
  @UseGuards(JwtAuthGuard)
  @ApiOperation({ summary: 'Change the visibility scope of a file (C2) — owner or admin' })
  setScope(
    @Param('id') id: string,
    @CurrentUser() user: any,
    @Body() body: { scope: 'personal' | 'team' | 'org'; teamId?: string | null },
  ) {
    return this.service.setScope(id, user.id, body.scope, body.teamId ?? null, user.role === 'admin');
  }

  @Delete(':id')
  @UseGuards(JwtAuthGuard)
  remove(@Param('id') id: string, @CurrentUser() user: any) {
    return this.service.remove(id, user.id);
  }
}
